GET http://localhost:3001/

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "pass123admin"
}

###

POST http://localhost:3001/user/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmRlNjZhOGEyMDAwYTdkODdjMmVkY2QiLCJpYXQiOjE2NTg5MDAwMjZ9.d0Fkm6Mhfe-xMG6HHg7xxdl-0_iCqoL_0cClNNanOzI"
}

###

POST http://localhost:3001/user/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmRlNjZhOGEyMDAwYTdkODdjMmVkY2QiLCJpYXQiOjE2NTg5MDAwMjZ9.d0Fkm6Mhfe-xMG6HHg7xxdl-0_iCqoL_0cClNNanOzI"
}

###

POST http://localhost:3001/group/accept-user/62dfb95d38ae100fdba44a35 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1N2ZlYWZkZTZkZDRiMTU2ZGYyMzciLCJpYXQiOjE2NTg5MjU2OTMsImV4cCI6MTY1ODkyNjY5M30.c-36uDm6Z87uCfqeLWexbZ4a0tu9YGdLPqLGytW5VIA

{
  "user": "62c510cae1d53c385fe3d8dc"
}

###

