GET http://localhost:3001/

###

POST http://localhost:3001/user/login
Content-Type: application/json

{
  "username": "danielcm2",
  "password": "pass123"
}

###

POST http://localhost:3001/user/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1MTBjYWUxZDUzYzM4NWZlM2Q4ZGMiLCJpYXQiOjE2NTcxODc1NDd9.2gPzMoSnhtcwIt_Ec0m_rQb3ZDTThQxEWiRHDpDDiI8"
}

###

PUT http://localhost:3001/user/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1MTBjYWUxZDUzYzM4NWZlM2Q4ZGMiLCJpYXQiOjE2NTcxODc1NDcsImV4cCI6MTY1NzE4ODU0N30.jVRA-F_rTV61MOwjdbKn2f9Pz_CulZU23Oa8weBUelA

{
  "oldPassword": "test123",
  "newPassword": "pass123"
}

###

DELETE http://localhost:3001/user/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1MTBjYWUxZDUzYzM4NWZlM2Q4ZGMiLCJpYXQiOjE2NTcxODc2MjB9.RJX6NSykrktljnV3bO1Bn62YCfqG4WzKUrK1A7eGFd0"
}